"""
Large narrative template pools for Nexus League Bot.

All lists are grouped by content_type used in bot_content_memory.
Template strings use {placeholders} for slot-filling after selection.
Plain strings need no formatting.
"""

# ---------------------------------------------------------------------------
# MATCHUP ANGLES  (content_type: "matchup_angle")
# Plain strings – the narrative lens for a game.
# ---------------------------------------------------------------------------
MATCHUP_ANGLES: list[str] = [
    "marquee showdown",
    "prove-it test",
    "style clash",
    "turnover battle",
    "quarterback-vs-pass-rush",
    "playoff pressure",
    "momentum swing",
    "must-win urgency",
    "division dominance",
    "redemption arc",
    "identity crisis",
    "power-ranking shakeup",
    "underdog opportunity",
    "trap-game alert",
    "second-half pivot",
    "early-season statement",
    "late-season gauntlet",
    "ground-game showdown",
    "air-raid duel",
    "defensive chess match",
    "turnover margin war",
    "field-position battle",
    "fourth-quarter resilience",
    "two-quarterback intrigue",
    "coaching chess match",
    "home-field advantage test",
    "road-warrior challenge",
    "pride-on-the-line clash",
    "wild-card positioning fight",
    "top-seed race",
    "play-in desperation",
    "division-title showdown",
    "spoiler mentality",
    "rivalry renewal",
    "breakout-performance platform",
    "veteran-vs-youth duel",
    "pace-of-play battle",
    "score-early-and-often showdown",
    "grind-it-out slugfest",
    "big-play threat encounter",
    "red-zone efficiency duel",
    "third-down conversion war",
    "big-game-mentality test",
    "roster-depth challenge",
    "slow-start correction",
    "hot-streak continuation",
    "statement victory opportunity",
    "must-protect-home clash",
    "road upset attempt",
    "first-half dominance battle",
]

# ---------------------------------------------------------------------------
# MATCHUP OPENERS  (content_type: "matchup_opener")
# Template strings – use .format(week=, away=, home=, angle=)
# ---------------------------------------------------------------------------
MATCHUP_OPENERS: list[str] = [
    "Week {week} puts {away} and {home} into a {angle} that should carry real weight.",
    "The {away} and {home} enter Week {week} with a matchup profile that feels like {angle}.",
    "There is a distinct {angle} feel to this Week {week} meeting between {away} and {home}.",
    "Week {week} gives {away} and {home} exactly what neither team wanted — a {angle}.",
    "If you wanted a clear {angle} on the schedule this week, {away} vs. {home} is it.",
    "This is not just another game; Week {week} frames {away} vs. {home} as a genuine {angle}.",
    "All the conditions are set for a {angle} when {away} visits {home} in Week {week}.",
    "{away} and {home} collide in Week {week} in what looks unmistakably like a {angle}.",
    "Heading into Week {week}, the {angle} between {away} and {home} is impossible to ignore.",
    "Week {week} delivers a {angle} as {away} takes on {home} with stakes on both sides.",
    "The calendar hits Week {week} and immediately spotlights a {angle} between {away} and {home}.",
    "{away} vs. {home} may end up being the defining {angle} of Week {week}.",
    "Every week needs a signature game, and in Week {week} the {angle} between {away} and {home} earns that billing.",
    "The {angle} narrative writes itself this week as {away} faces {home} in Week {week}.",
    "When the schedule-makers drew up Week {week}, they knew {away} vs. {home} would land as a {angle}.",
    "Circled on the board as a {angle}, the Week {week} bout between {away} and {home} finally arrives.",
    "Few games in Week {week} carry the {angle} energy that {away} vs. {home} brings to the table.",
    "Before anything else gets decided, {away} and {home} must settle this {angle} in Week {week}.",
    "Week {week} wastes no time setting up a {angle} when {away} squares off against {home}.",
    "The {angle} storyline that has been building peaks in Week {week} with {away} vs. {home}.",
    "{home} hosting {away} in Week {week} turns this into a textbook {angle}.",
    "League-wide attention shifts to the {angle} pitting {away} against {home} in Week {week}.",
    "As Week {week} kicks off, the {angle} between {away} and {home} stands out immediately.",
    "A {angle} this week: {away} travels to face {home} with Week {week} on the line.",
    "Step inside a classic {angle} as {away} battles {home} during Week {week}.",
    "Week {week} has plenty of games, but the {angle} between {away} and {home} leads the slate.",
    "Under the Week {week} spotlight: a {angle} that could reshape the conversation around both {away} and {home}.",
    "The {angle} setting is perfect for Week {week} — {away} has answers to find and {home} has something to protect.",
    "There is no soft landing in Week {week}; {away} meets {home} in a pure {angle}.",
    "Both sides know what this is: a {angle} in Week {week} between {away} and {home} that could define the next month.",
    "On paper and in practice, Week {week}'s matchup between {away} and {home} screams {angle}.",
    "The stakes arrive early this week, wrapped inside the {angle} that is {away} vs. {home} in Week {week}.",
    "Week {week} presents {away} and {home} with a clear {angle} they cannot sidestep.",
    "It may be labeled just another Week {week} game, but {away} vs. {home} is really a {angle}.",
    "Strip away the schedule noise and you find a straightforward {angle} between {away} and {home} in Week {week}.",
    "The {angle} energy is palpable as {away} and {home} prepare to clash in Week {week}.",
    "One of the more compelling {angle} setups in recent weeks comes in Week {week}: {away} at {home}.",
    "{away} vs. {home} sets the Week {week} tone — the {angle} flavor here is hard to miss.",
    "Brace for a {angle} as {away} and {home} lock horns in one of Week {week}'s top contests.",
    "Week {week} opens with a {angle} narrative as {away} rolls into town to face {home}.",
    "The Week {week} spotlight lands squarely on the {angle} between {away} and {home}.",
    "A {angle} headline writes itself when {away} and {home} share a Week {week} stage.",
    "Not every game earns the {angle} label, but {away} vs. {home} does heading into Week {week}.",
    "Week {week} serves up a signature {angle} — {away} and {home} under the same roof.",
    "The {angle} theme runs straight through the Week {week} matchup of {away} vs. {home}.",
    "From the first snap to the last whistle, Week {week}'s {away}-{home} contest is a {angle}.",
    "When {away} and {home} meet in Week {week}, the {angle} context looms over every possession.",
    "Tee it up: Week {week} offers a made-for-TV {angle} when {away} faces off against {home}.",
    "In the middle of all the Week {week} action sits a legitimate {angle}: {away} vs. {home}.",
    "The {angle} heat is turned up as {away} and {home} prepare for a Week {week} collision.",
    "Week {week} is the backdrop for a {angle} that neither {away} nor {home} can afford to lose.",
    "Whether fans circled it or not, {away} vs. {home} in Week {week} is a {angle} worth watching.",
    "No fluff, no filler — just a clean {angle} when {away} visits {home} in Week {week}.",
    "It is shaping up to be a memorable Week {week}, and the {angle} between {away} and {home} is the reason.",
    "Both sidelines know the {angle} stakes are high when {away} meets {home} in Week {week}.",
    "A {angle} with real consequences: {away} and {home} collide in Week {week}.",
    "The {angle} aura surrounding {away} vs. {home} makes this Week {week}'s centerpiece.",
    "Week {week} delivers its defining {angle} when {away} and {home} take the field together.",
    "Hard to find a purer {angle} than {away} at {home} in Week {week}.",
    "A genuine {angle} awaits as {away} and {home} settle in for what could be a pivotal Week {week} game.",
    "The {angle} tension has been building, and Week {week} is finally the release valve — {away} vs. {home}.",
    "What makes Week {week} special: the {angle} brewing between {away} and {home} since the start of the season.",
    "When you need a {angle} to define the week, {away} vs. {home} in Week {week} answers the call.",
    "The {angle} at its finest: {away} and {home} matching up with real Week {week} stakes.",
    "Week {week} does not lack for intrigue, but the {angle} involving {away} and {home} tops the list.",
    "Add the {angle} to the Week {week} ledger: {away} at {home}, and both teams have something to say.",
    "A {angle} with playoff implications hiding inside every snap — that is {away} vs. {home} in Week {week}.",
    "If there was ever a week to stage a {angle}, it is Week {week} with {away} hosting {home}.",
    "Fans are getting a {angle} in Week {week} as {away} and {home} go head to head.",
    "The {angle} in Week {week} is fully loaded: {away} versus {home}, winner gains ground.",
    "Every week has its signature game, and in Week {week} it is the {angle} between {away} and {home}.",
    "When {away} and {home} meet, the {angle} stakes in Week {week} could not be clearer.",
    "On the surface it is just Week {week}, but beneath it is a {angle} that both {away} and {home} need to win.",
    "The {angle} dynamic running through Week {week} comes to a head when {away} visits {home}.",
    "Week {week}: {away} vs. {home} — the textbook definition of a {angle}.",
    "This is the {angle} moment for both teams: Week {week}, {away} against {home}.",
    "A {angle} is baked into the Week {week} schedule, and the headliner is {away} vs. {home}.",
    "The {angle} chapter of both teams' seasons arrives simultaneously in Week {week} — {away} at {home}.",
    "Week {week} belongs to this {angle}: {away} and {home} put their credentials to the test.",
    "Lights. Camera. {angle}. Week {week} pits {away} against {home} in the spotlight game.",
    "The {angle} meter is pinned heading into Week {week}'s contest between {away} and {home}.",
    "Every possession will carry {angle} weight as {away} and {home} collide in Week {week}.",
    "The {angle} makes every snap in Week {week} feel bigger when {away} squares off against {home}.",
    "A pure {angle} — that is the best description for {away} vs. {home} in Week {week}.",
    "Week {week} frames it perfectly: a {angle} where {away} and {home} each have everything to prove.",
    "The {angle} between {away} and {home} gets its moment in Week {week}.",
    "In Week {week}, the {angle} between these two programs bubbles to the surface when {away} meets {home}.",
    "{away} at {home} in Week {week} — call it what it is: a {angle} with serious ramifications.",
    "The {angle} vibes are strong all week, and they boil over when {away} faces {home} in Week {week}.",
    "With {angle} as the backdrop, {away} and {home} take center stage in Week {week}.",
    "Week {week} draws the {angle} card, and {away} vs. {home} is dealt the biggest hand.",
    "The {angle} between {away} and {home} in Week {week} is the kind of game the rest of the league watches.",
    "Call the scouting report what it is — a {angle} — because Week {week} matchup {away} vs. {home} earns that label.",
    "A full {angle} experience is on the menu in Week {week} when {away} takes on {home}.",
    "The {angle} storyline in Week {week} belongs to {away} and {home} — and the winner earns the better narrative.",
    "Strap in for a {angle} as the Week {week} schedule delivers {away} vs. {home}.",
    "Week {week}'s most captivating {angle} starts when {away} and {home} kick off.",
    "The {angle} edge is real for both sides as {away} and {home} meet up in Week {week}.",
    "Everything about Week {week} screams {angle} when you look at {away} vs. {home}.",
]

# ---------------------------------------------------------------------------
# MATCHUP BODIES  (content_type: "matchup_body")
# Template strings – use .format(away=, home=)
# These are the middle-sentence story lines.
# ---------------------------------------------------------------------------
MATCHUP_BODIES: list[str] = [
    "Both {away} and {home} arrive with something to settle and a point to make.",
    "{away} needs this performance as much as any this season; {home} is ready to make it complicated.",
    "The story lines around {away} and {home} are converging in the most interesting way possible.",
    "{home} has been building toward a game like this; {away} is hoping to disrupt that momentum.",
    "{away} has shown flashes of their ceiling — Saturday is a chance to hit it against {home}.",
    "This is the game both {away} and {home} have been circling since the schedule came out.",
    "{home}'s execution has been sharpest when the pressure is highest — {away} brings the pressure.",
    "Neither {away} nor {home} can afford a slip-up, which makes every possession feel magnified.",
    "The contrast in styles between {away} and {home} makes this a legitimate chess match.",
    "{away} has everything to gain; {home} has a record to protect.",
    "What {home} does up front will determine how much trouble {away} has operating its offense.",
    "{away} travels knowing its identity is on trial; {home} wants to be the verdict.",
    "This is a team-building moment for {away} — a win here changes the conversation.",
    "{home} is not just looking for a win; they want to make a statement against {away}.",
    "Watch the third-down efficiency battle between {away} and {home} — that will decide the game.",
    "{away}'s red-zone production will face its toughest test against {home}'s defense.",
    "The turnover margin battle between {away} and {home} is the key subplot no one should overlook.",
    "{home} controls time of possession best when everything clicks — {away} must keep them off balance.",
    "{away} has responded well to adversity this season; {home} wants to provide a fresh dose of it.",
    "The physicality at the line of scrimmage will set the tone for both {away} and {home}.",
    "{away} is at a crossroads; a win over {home} would quiet every critic.",
    "For {home}, this is about proving their standing is legitimate against a real test like {away}.",
    "Whether {away} can protect the ball will matter just as much as whether {home} can create turnovers.",
    "The offensive tempo that {away} wants to play at clashes directly with what {home} allows.",
    "There is a clear battle of identity: {away}'s offensive system against {home}'s defensive scheme.",
    "Complementary football will be the key — the team that gets it from both sides wins between {away} and {home}.",
    "{home}'s preparation all season has pointed toward winning games like this one against {away}.",
    "Big plays will define this one — whichever of {away} or {home} creates them first changes the energy.",
    "{away} wants to run the ball effectively; {home} is committed to stopping it. Something has to give.",
    "This game features an interesting matchup at every level of the field — {away} and {home} are closely matched.",
    "Watch the second-quarter possession battle carefully — {away} and {home} each build momentum differently.",
    "The team that controls field position between {away} and {home} will find the margin they need.",
    "Special teams could be a decisive factor, and both {away} and {home} know it going in.",
    "{away} keeps it close by grinding; {home} keeps it close by capitalizing on mistakes. Something different has to happen.",
    "The margin in this game will be thin — {away} and {home} are matched too well for it to blow open.",
    "If {home} can force a quick three-and-out, the crowd energy shifts fast in their favor against {away}.",
    "{away} needs to start fast — falling behind against a team like {home} is a dangerous position.",
    "Both {away} and {home} rely on establishing a rhythm; the team that does it first sets the tone.",
    "The talent difference is smaller than the records suggest — {away} vs. {home} will come down to execution.",
    "When the game gets tight in the fourth quarter, leadership under pressure will separate {away} and {home}.",
    "This game will test depth; both {away} and {home} have had to rely on their roster more than expected.",
    "The pressure-handling ability of each team gets exposed on the road — one of these teams is about to find out.",
    "{away} made adjustments last week that could translate into a big performance against {home}.",
    "{home} has a way of dictating the pace of games — {away} will need to have an answer for that.",
    "Both teams live and die by the same principles; {away} vs. {home} is a measuring-stick matchup of execution.",
    "{away} is relying on its top producer more than any team in the league right now — {home} knows it.",
    "{home} wins when it forces the opposition to play a style that suits {home}'s defense — that is the plan against {away}.",
    "The game plan from both {away} and {home} will be revealed in the first fifteen minutes.",
    "There is a genuine clash of philosophies between {away} and {home} that makes this game fascinating.",
    "Both {away} and {home} are capable of the kind of performance that changes the season narrative.",
    "The hunger in both locker rooms is real — {away} and {home} both believe this is a winnable game.",
    "Game-script manipulation will be crucial; {away} and {home} both have a clear preferred mode of operation.",
    "{home} thrives when it can lean on its strengths; {away} is specifically built to challenge those strengths.",
    "Whoever wins the turnover battle between {away} and {home} will likely win the game outright.",
    "{away}'s coaching staff has prepared specifically for this moment; {home} will have a counter-plan.",
    "The pace of this game matters enormously — {away} wants it quick, {home} wants it slow.",
    "Both teams understand that the standings implications of this game extend far beyond Week {week}.",
    "There is nothing predictable about {away} vs. {home} — both teams have layers that show up in big moments.",
    "Talent is even, preparation is even, stakes are high — {away} and {home} will need to find the edge somewhere.",
    "{home} defending home field successfully this season would be a major statement; {away} is the biggest test yet.",
    "This is a game where game-management decisions from both sidelines could swing the final outcome.",
    "{away} versus {home} is a game about imposing will — and both teams believe they can do exactly that.",
    "Physicality, preparation, and execution will decide who walks away the winner between {away} and {home}.",
    "Every timeout, every challenge, every fourth-down decision counts when {away} and {home} play this close.",
    "{away} has the ceiling to win; {home} has the consistency to keep {away} from reaching it.",
    "{home} has not blinked under pressure yet — {away} is here to force the first time.",
    "This is the game that will get referenced all season long regardless of which team wins.",
    "{away} controls what it can control; {home} is excellent at taking the controllables away.",
    "Both {away} and {home} have turned late-game deficits into wins this season — this one could go to the wire.",
    "The offensive weapon depth of {away} gets its biggest test against the defensive scheme {home} has constructed.",
    "{home} at full strength is difficult to beat; {away} knows the only way to win is to make the game uncomfortable.",
    "Simplify the scouting: {away} has been building for this type of matchup, and {home} has been preparing for it.",
    "There is genuine mutual respect between these programs, but on game day {away} and {home} are out for wins.",
    "The game within the game between {away} and {home} is fascinating — every position group has a storyline.",
    "{away} needs its defense to carry early — if it does, the offense will find its footing against {home}.",
    "Both {away} and {home} have healthy rosters heading in, which means the better team on that day wins.",
    "All the preparation in the world gets tested in real time when {away} and {home} hit the field.",
    "The first score of this game will carry psychological weight — neither {away} nor {home} can afford to trail.",
    "{home} plays its best when operating in a comfort zone — {away} is specifically here to disrupt that.",
    "{away} thrives on pace and pressure; {home} is known for patience and structure. The contrast is compelling.",
    "What makes {away} vs. {home} so interesting is how similar their formulas for winning actually are.",
    "Both teams will attack the opponent's weakness — the question is which side finds it first.",
    "The player-to-player matchups on the field between {away} and {home} are elite on multiple levels.",
    "This game requires total-roster football; one unit cannot carry {away} or {home} to a win here.",
    "{away} needs a clean game; {home} needs an aggressive game. The strategy difference will be clear from the start.",
    "{home} sets the physical tone early in most games; {away} must establish their own identity first.",
    "It is a battle of schemes and adjustments — and both head coaches of {away} and {home} are at their best in this setting.",
    "The late-game composure of {away} will be tested by everything {home} throws at them.",
    "There is no guaranteed outcome here — {away} and {home} are as evenly matched as any game on the schedule.",
    "Both {away} and {home} have earned the right to compete on this stage through weeks of grind.",
    "{away} does not fear the moment, and neither does {home}. That is what makes this game must-see.",
    "The game that defines a season can look just like any other Week {week} matchup — until it doesn't.",
    "Strip away the records and you still have two teams — {away} and {home} — that are capable of winning this.",
    "This game is going to the fourth quarter; both {away} and {home} are built for close games.",
    "{home} rarely plays loose with a lead; {away} will need to manufacture one to change the dynamic.",
    "The real battle in {away} vs. {home} is which team can best execute its identity under maximum pressure.",
    "Big-game tendencies reveal themselves when the margin is tight — that is exactly where {away} and {home} are headed.",
    "Both teams leave their best on the field in games like this one; {away} vs. {home} will be no different.",
    "{away} has momentum; {home} has a home crowd. The advantage swap happens one possession at a time.",
    "Every single snap in {away} vs. {home} will matter — this is about who wants it more.",
]

# ---------------------------------------------------------------------------
# MATCHUP STAKES  (content_type: "matchup_stakes")
# Plain strings – why this game matters.
# ---------------------------------------------------------------------------
MATCHUP_STAKES: list[str] = [
    "This one has direct leverage on the playoff picture and weekly momentum.",
    "The winner grabs valuable room in the standings race while the loser absorbs pressure.",
    "A result here can quickly change perception and seeding paths across the league.",
    "A win reshapes the standings; a loss tightens the screws heading into the back half.",
    "Both teams are fighting for the same space in the standings — only one can have it.",
    "The loser walks away with fewer options; the winner opens new ones.",
    "Playoff positioning is the subtext behind every play in this game.",
    "A win here keeps the season narrative moving forward; a loss forces a rewrite.",
    "The standings ripple effect from this game will be felt league-wide.",
    "Every game matters late in the year, but this one carries multi-week implications.",
    "The winner gains breathing room; the loser gets squeezed from multiple directions.",
    "A quality win here changes the tone of the rest of the season for the victor.",
    "This is a game about leverage — and only one team gets to claim it after Sunday.",
    "The playoff math gets cleaner for the winner and harder for the loser.",
    "There is a real chance this game becomes a season-defining result for one of these teams.",
    "Both squads need a win to keep their positioning intact — something has to break.",
    "The loser cannot afford a two-game slide after this; the winner can finally breathe.",
    "Seeding, momentum, and confidence are all on the table in this matchup.",
    "The implications here extend well beyond this week's box score.",
    "One team gains ground; the other loses it. That is what makes this game essential.",
    "With playoff spots limited, every game in this part of the schedule is a must-win candidate.",
    "This result will be referenced when the final standings are sorted.",
    "The winner grabs a signature win; the loser must start repairing damage immediately.",
    "Head-to-head tiebreakers, seed positioning, and momentum all hinge on this result.",
    "The league standings do not lie — whoever wins this game earns the right to feel better about their path.",
    "Everything between these two teams will be decided in this game, at least for now.",
    "A win here is worth more than two points — it shifts the conversation at the top of the standings.",
    "There is no clean way to lose this game and feel fine about where things stand.",
    "The pressure to perform comes with postseason futures on the line.",
    "The winner earns the right to control their own destiny for at least another week.",
    "A loss here creates urgency; a win here creates separation.",
    "The team that wins this game gets to play from ahead — a massive advantage this late in the year.",
    "This is not just about momentum — this is about controlling the narrative entering the final stretch.",
    "The stakes are simple: win and keep the pressure on; lose and face it yourself.",
    "The loser will need help to reach their goal; the winner can get there alone.",
    "Both teams understand this is the kind of game that appears in the retrospective reel of their season.",
    "When the seedings shake out, this result could be the one that made the difference.",
    "A win here would be the biggest result either team has earned this season.",
    "Whoever walks away with the W has the better case for where they deserve to sit in the standings.",
    "This game is a chess match with playoff implications on every piece of the board.",
    "Confidence is at stake as much as the two points in the standings.",
    "The loser gets a wake-up call they cannot ignore; the winner proves they belong.",
    "This game sets the tone for the final portion of the regular season.",
    "A win here can single-handedly change the trajectory of the rest of the schedule.",
    "The playoff picture gets clearer for one of these teams after this game — and cloudier for the other.",
    "Big games require big performances — this one has career-defining weight for players on both sides.",
    "Two games from this point could be separated by today's result — the margin matters.",
    "The winner earns respect; the loser earns urgency. Both matter in a tight league.",
    "One win can turn a struggling team's season around — this is that game.",
    "The loser faces an uphill climb; the winner opens a door they cannot afford to let close.",
    "Both teams have everything to gain and everything to lose from a single result.",
    "This is exactly the type of game that separates good teams from great ones.",
    "The difference between competing and contending lives in games exactly like this one.",
    "Nothing will be the same after this game for one of these teams.",
    "Two teams fighting for the same future meet this week — only one can claim it.",
    "The winner earns a week of confidence; the loser earns a week of serious self-reflection.",
    "This is the measuring-stick game both teams needed to know exactly where they stand.",
    "The season does not end here, but the path to the postseason could get decided.",
    "Both teams are in the window where every result matters — and this one matters most.",
    "The loser will need to win every remaining game to recover from a loss here.",
    "A dominant performance here sends a message to the rest of the league — and both teams know it.",
    "Momentum in this league can flip fast, and this game is a critical pressure point.",
    "The standings are tight enough that this game could move multiple teams simultaneously.",
    "A win here is the kind of result that echoes in the locker room for weeks.",
    "The winner keeps the dream alive; the loser has to find a different path.",
    "Both programs are measured by their ability to win games exactly like this one.",
    "The team that wins here owns the next chapter of both teams' seasons.",
    "Playoff seeding implications aside, the psychological edge from a win here is enormous.",
    "This is a game both teams will remember — the question is which way they remember it.",
    "The results board does not care about moral victories — this game demands a win from both teams.",
    "Whether or not the season comes down to one game, this feels like that game.",
    "There are no easy path adjustments after a loss here — both teams understand the stakes.",
    "A big win today means a better seat at the table when the final seedings are announced.",
    "The winner controls their own story for another month; the loser must rely on others.",
    "The playoff hunt gets either simpler or much harder after this result — there is no middle ground.",
    "Momentum, confidence, and seeding all flow through this single game result.",
    "The team that wins gets to dictate the narrative; the team that loses must respond to it.",
    "Everything the two teams have built this season gets tested in one decisive game.",
    "The winner earns a crucial leg up in the standings race; the loser needs to regroup fast.",
    "Win or lose, this game will echo through the locker rooms of both teams for weeks.",
    "A wire-to-wire win here tells the league exactly where you stand heading into the final push.",
    "The difference between winning the division and chasing a wild card could start right here.",
    "Both teams need this win more than they might admit — that is what makes it compelling.",
    "The season is not decided today, but the tone for the rest of it absolutely is.",
    "This is a game about want-to as much as it is about talent — both teams have the talent.",
    "A win brings clarity; a loss brings questions that take weeks to answer.",
    "The standings implications of this game make it the most important result of the week.",
    "The pressure is mutual and the stakes are identical — whoever handles it better wins.",
    "Both teams are one big result away from changing their entire season arc — this is that result.",
    "The win-loss record is the story, and this game writes the next line.",
    "Keeping pace with the teams above, staying ahead of the teams below — this game handles both.",
    "The winner earns a chance to prove themselves in even bigger games ahead.",
    "Lose this game and it is catch-up mode; win it and it is cruise control — relatively speaking.",
    "This is the game that will define the mentality of both teams for the rest of the season.",
    "The stakes are as high as they will be all year for teams in this position.",
    "Two teams trying to survive and advance meet in the most direct way possible today.",
    "The result from this game will be one of the first things the analysts reference come playoff time.",
    "This is the game both teams knew was coming — the one that sorts out the real contenders.",
]

# ---------------------------------------------------------------------------
# PLAYER WHY LINES – PASSING  (content_type: "player_why_passing")
# Template strings – use .format(first=, team_name=)
# ---------------------------------------------------------------------------
PLAYER_WHY_PASSING: list[str] = [
    "{team_name} goes as {first} goes — their offense runs through his arm.",
    "When {first} is on, {team_name} controls the game; watch his turnover count.",
    "{first} is the engine of {team_name}'s offense and a key player to track.",
    "{first} protects the football and {team_name} wins — that is the formula.",
    "Everything {team_name} does offensively traces back to what {first} can create.",
    "{first}'s ability to extend plays is what keeps {team_name}'s offense unpredictable.",
    "When the game gets tight, {team_name} is going to need {first} to deliver.",
    "{first} reads defenses better than anyone on the {team_name} roster — that instinct is priceless.",
    "{team_name} moves the chains when {first} can find the second-read quickly.",
    "Ask any defensive coordinator — containing {first} is the top priority against {team_name}.",
    "{first} makes {team_name}'s entire playbook viable; without him running clean, nothing flows.",
    "The {team_name} offense has a higher ceiling when {first} is operating with rhythm.",
    "{first}'s pocket presence defines the pace of {team_name}'s offense from the first snap.",
    "Ball security from {first} will be the statistic worth watching most closely for {team_name}.",
    "When {first} is sharp with his footwork, {team_name} is nearly unstoppable in the passing game.",
    "{first} has the arm to keep {team_name} in any game, no matter the score.",
    "The pre-snap read ability {first} brings gives {team_name} a consistent advantage.",
    "{team_name}'s best offensive plays happen when {first} trusts his eyes and fires on time.",
    "If {first} gets comfortable early, {team_name}'s defense gets shorter fields all day.",
    "What {first} does under pressure tells the story of {team_name}'s offensive identity.",
    "{first} stands between {team_name} and a long day offensively — he needs to be at his best.",
    "The chemistry {first} has built with his pass catchers is what makes {team_name} dangerous.",
    "{team_name} leans on {first} to set up the run and establish the pass; both will matter today.",
    "{first} threading the needle on third and medium is the key to {team_name} staying on schedule.",
    "Whether {team_name} can protect {first} long enough to let the routes develop is the central question.",
    "{first} operating from a clean pocket makes {team_name}'s entire playbook dangerous.",
    "The rhythm {first} builds in the first half determines whether {team_name} can score late.",
    "{team_name} averages nearly a touchdown more per game when {first} stays under 1 interception.",
    "The ability of {first} to diagnose pressure presnap gives {team_name} a measurable edge.",
    "Watch {first}'s eyes — when he confirms coverage early, {team_name} hits on the big play.",
    "{team_name} needs {first} to be the best player on the field today, not just the best on their roster.",
    "Turnover-free football from {first} is the blueprint for a {team_name} victory.",
    "{first}'s release speed from the pocket creates issues for even the best pass rushes — {team_name} benefits.",
    "If {first} can be efficient before the defense adjusts, {team_name} controls the game script.",
    "{team_name} builds its entire weekly game plan around what {first} can take away from a defense.",
    "The efficiency numbers from {first} this season speak to how central he is to {team_name}'s identity.",
    "No one in this game matters more to the final outcome than {first} does to {team_name}.",
    "The way {first} processes information in real time is the most underrated part of {team_name}'s offense.",
    "{team_name} lives and dies by {first}'s arm — today they need it to carry them.",
    "{first} has the tools to carve up any defense; the question is whether he gets the time to use them.",
    "{team_name} has built its scoring around {first}'s ability to create when the play breaks down.",
    "The clutch factor {first} brings to {team_name} is what separates them from teams with similar records.",
    "{first} is at his best when the game gets tight — {team_name} may need to find out how good that is.",
    "What {first} does on third downs is the statistical backbone of {team_name}'s offensive production.",
    "{first}'s ability to go through reads without turning the ball over is {team_name}'s most critical skill.",
    "The yards-after-throw that {first} generates through accuracy make {team_name}'s receivers better.",
    "{team_name}'s ability to score in the red zone is directly tied to {first}'s precision short-area throws.",
    "Watch {first} in the two-minute drill — it is when his preparation and instincts for {team_name} show up most.",
    "{first} can take over a game with his arm; the defense today must decide how much they respect that threat.",
    "{team_name} gets into its best rhythm when {first} can throw with timing rather than force.",
    "Protecting {first} is priority one for {team_name}'s offensive line — the rest of the game follows.",
    "{first} at full operational confidence is the most difficult read for a defense facing {team_name}.",
    "Everything that makes {team_name} dangerous starts with {first} seeing the field clearly.",
    "{first} has a way of making tough throws look routine — {team_name} depends on that composure.",
    "The decisiveness {first} shows in the pocket is what makes {team_name}'s offense tick.",
    "When {first} is in sync with the game plan, {team_name} does not need to rely on the run.",
    "{first} going through his reads at full speed is what makes the {team_name} offense difficult to prepare for.",
    "The touch {first} shows on intermediate routes is a critical edge for {team_name} in this matchup.",
    "{team_name}'s playmakers become exponentially more dangerous when {first} is delivering on time.",
    "{first}'s command of the two-minute offense has saved {team_name} multiple times — today that could matter again.",
    "{first} makes the offense around him better; when he plays well, {team_name} raises its floor.",
    "The snap count tempo that {first} sets for {team_name} keeps the defense guessing all game.",
    "If {first} can draw a free release or two early, {team_name}'s entire offensive menu opens up.",
    "{team_name}'s best chance of winning involves {first} staying on-script without costly mistakes.",
    "One clutch drive from {first} in the fourth quarter has decided three {team_name} games already.",
    "{first}'s footwork in the pocket disguises his intention long enough for {team_name} to win routes.",
    "The way {first} commands the offensive line communication adds a subtle edge for {team_name}.",
    "{team_name}'s path to victory runs directly through what {first} does with the ball in his hands.",
    "No one generates more excitement in a {team_name} drive than {first} when he is locked in.",
    "{first} making the tough throw under duress is the play that keeps {team_name} in games.",
    "The ceiling in this game for {team_name} is set by how much {first} can open up the field.",
    "When {first} gets into a zone, opposing defenses against {team_name} simply have no answer.",
    "{team_name} is at its best when {first} distributes efficiently across multiple pass catchers.",
    "{first} understanding the opponent's tendencies presnap gives {team_name} a real tactical advantage.",
    "The shot-play decision-making {first} shows is the direct result of his preparation for {team_name}.",
    "{first} rarely loses the margin battle — the small decisions he makes correctly keep {team_name} ahead.",
    "Competing against a prepared defense, {first}'s improvisation keeps {team_name} efficient.",
    "For {team_name} to win today, {first} must play his best version — and he is capable of exactly that.",
    "The experience {first} brings to clutch situations makes {team_name} a team that never quite feels out of it.",
]

# ---------------------------------------------------------------------------
# PLAYER WHY LINES – RUSHING  (content_type: "player_why_rushing")
# Template strings – use .format(first=, team_name=)
# ---------------------------------------------------------------------------
PLAYER_WHY_RUSHING: list[str] = [
    "{team_name}'s ground game is built around {first}'s legs this season.",
    "{first} sets the tone for {team_name}; a big rushing day opens the playbook.",
    "Everything starts for {team_name} when {first} can find running room.",
    "{first} getting north-south early gives {team_name} the game script they want.",
    "When {first} averages over four yards a carry, {team_name} almost never loses.",
    "{team_name}'s ability to protect the lead runs directly through {first}'s legs.",
    "{first} is the workhorse who keeps {team_name}'s offense balanced and their defense fresh.",
    "The physical toll {first} puts on defenses benefits {team_name}'s passing game later in games.",
    "When {first} churns positive yards after contact, {team_name} controls the second half.",
    "{first}'s vision at the line of scrimmage is what makes the {team_name} run game dangerous.",
    "Stopping {first} early is the only way to slow {team_name}'s offensive momentum.",
    "{team_name}'s clock management and game control both depend on {first} producing on the ground.",
    "The more carries {first} handles, the fresher the {team_name} defense stays on the other side.",
    "{first} in the open field is a highlight waiting to happen — {team_name} creates those chances.",
    "{team_name} wins in the trenches when {first} can see the cutback lanes developing.",
    "Every successful run by {first} sets up a favorable passing down for {team_name}.",
    "{first}'s ability to make the first tackler miss is why {team_name} commits to the run.",
    "{team_name} needs {first} productive and healthy — when both are true, they are hard to stop.",
    "{first} draws eight-man boxes, and that is when {team_name}'s play-action game becomes a weapon.",
    "Whether it is between the tackles or outside the tackles, {first} finds a way to produce for {team_name}.",
    "The yards-after-contact numbers that {first} posts are exactly what {team_name}'s game plan relies on.",
    "{first} operating in space forces defensive overcommitment — {team_name} uses that to open the passing lanes.",
    "Four-down territory anywhere near midfield gets interesting when {team_name} has {first} in the backfield.",
    "Protecting the football and protecting the lead both go through {first} for {team_name}.",
    "When {first} is running angry, {team_name} becomes the most difficult team in the league to slow down.",
    "{team_name}'s third-down conversion rate is tied directly to the success {first} generates on first and second down.",
    "{first} sets a physical tone that the offensive line can build on, snap after snap for {team_name}.",
    "The deceptive patience {first} shows at the line of scrimmage creates problems for any front seven against {team_name}.",
    "{team_name} can flip field position quickly whenever {first} breaks a run to the second level.",
    "{first} picking up the tough yards in short-yardage situations keeps {team_name} moving the chains.",
    "The game-speed decisiveness that {first} shows has produced clutch conversions for {team_name} all season.",
    "{first}'s impact is felt long after his carry — the mentality he brings wears down defenses for {team_name}.",
    "When {first} gets going early, the play-action pass opens up and {team_name} becomes two-dimensional.",
    "{team_name} earns its toughest yards through {first} — and those yards often decide games.",
    "{first}'s burst through the line of scrimmage creates cutback opportunities that spring big gains for {team_name}.",
    "The way {first} sets up the defense on outside runs before cutting back is a joy to watch from {team_name}.",
    "{team_name} designs its best run concepts specifically to get {first} into open space.",
    "When defenders hesitate, {first} punishes them — {team_name} counts on that instinct.",
    "{first}'s ability to stay in bounds and run the clock is as valuable as any big gain for {team_name}.",
    "The combination of {first}'s burst and his ability to break tackles gives {team_name} an elite ground option.",
    "{team_name} at peak efficiency always features {first} with 15 or more quality carries.",
    "{first}'s footwork before the handoff gives nothing away — {team_name} uses that unpredictability.",
    "You cannot game-plan {first} perfectly because he improvises so well for {team_name}.",
    "{first} in the fourth quarter, when defenses are tired, is the situation {team_name} builds the game plan around.",
    "The contact balance {first} shows keeps him upright after hits that would stop most backs — {team_name} benefits all game.",
    "{team_name}'s ability to establish the run sets up their best plays — {first} is the reason that works.",
    "{first} needs to find two or three explosive runs for {team_name} to fully control the game tempo.",
    "When {first} runs through arm tackles and breaks into the second level, the {team_name} sideline energizes.",
    "The tempo that {first} dictates with his rushing style is the emotional driver of {team_name}'s offense.",
    "{first} is at his best when the game gets physical — and today's game is going to be physical.",
    "Every defense understands stopping {first} is the mission; few have a consistent answer for {team_name}.",
    "{team_name}'s run blocking scheme specifically creates the lanes {first} exploits best.",
    "A productive {first} means a manageable third down for {team_name} — that is the formula that wins.",
    "{first}'s ability to move the pile in short-yardage is one of the most reliable skills on {team_name}'s roster.",
    "The elusiveness {first} brings in the open field turns three-yard gains into twelve-yard explosions for {team_name}.",
    "{team_name} game-plans to get {first} the ball in space as often as the defense allows — opponents know it.",
    "When {first} is working, {team_name} can dictate the pace and possession time of the entire game.",
    "{first} breaking a long run changes the emotional energy on the {team_name} sideline immediately.",
    "The willingness {first} shows to pick up the extra yard after contact defines the {team_name} run game.",
    "{team_name}'s most dangerous play-calls all start with the defense needing to account for {first}.",
    "{first} mastering the subtle timing of the gap means the {team_name} offensive line gets maximum returns.",
    "Consistent production from {first} on early downs is the gateway to {team_name}'s best play-action opportunities.",
    "{team_name} feeds {first} when the game is on the line — that is not an accident.",
    "{first} at the top of his game running through a tired defense is the cleanest path to a {team_name} win.",
    "{first}'s knack for getting a chunk gain on second-and-long keeps {team_name}'s drives alive.",
    "Winning the line of scrimmage behind {first} is the ground floor of every {team_name} offensive possession.",
    "When {first} is clicking, {team_name} is playing its best football — and the team knows it.",
    "The opponent's defensive coordinator has spent the week scheming to slow {first} down; he usually finds a way anyway.",
    "{first} has the instinct to hit it fast when the hole opens — {team_name} gets yards others do not.",
    "A clean, balanced game from {first} gets {team_name} into the fourth quarter with the lead.",
    "{team_name} stacks the run-game efficiency chart largely because of how {first} handles contact situations.",
    "{first} quietly leads the most important ground game in {team_name}'s division — defenses have to respect it.",
    "The effort {first} shows on every carry regardless of gain length is the standard {team_name} runs by.",
    "{first} does not wait for perfect blocking — he makes the best of what he is given for {team_name}.",
    "Rushing {first} behind their best blockers on key downs is the simple strategy that keeps {team_name} winning.",
    "When {first} plants his foot and cuts, it is already too late for most linebackers to respond against {team_name}.",
    "The patience {first} shows before hitting the accelerator is a skill most {team_name} opponents underestimate.",
    "{team_name} trusts {first} in every game situation — that trust is well earned by what he has done this season.",
    "{first} has forced more missed tackles than almost anyone in the league, making every {team_name} drive dangerous.",
]

# ---------------------------------------------------------------------------
# PLAYER WHY LINES – DEFENSE  (content_type: "player_why_defense")
# Template strings – use .format(first=, team_name=)
# ---------------------------------------------------------------------------
PLAYER_WHY_DEFENSE: list[str] = [
    "{first} is {team_name}'s disruptor — a turnover or pressure from him can flip the game.",
    "If {first} gets into the backfield early, {team_name} can control the line of scrimmage.",
    "{first} leads {team_name}'s defense; his presence creates problems for any offense.",
    "Disruption from {first} is what turns a good {team_name} defense into an elite one.",
    "{first} makes the quarterback uncomfortable just by lining up — {team_name} wins when that happens.",
    "The offense has to account for {first} on every single snap; that changes everything for {team_name}.",
    "When {first} is active and disruptive, {team_name} can pin their ears back and create havoc.",
    "{first}'s football IQ gives {team_name} the scheme disguise that keeps offenses off-balance.",
    "The pass-rush ability of {first} turns a quick passing game into a difficult proposition against {team_name}.",
    "{first} is equally dangerous against the run and the pass — {team_name} uses that versatility constantly.",
    "Forcing off-platform throws or turnovers, {first} shifts the momentum math for {team_name}.",
    "{team_name}'s pressure packages are designed to feature {first} — and they work.",
    "{first} in the right gap at the right time has flipped games for {team_name} all season.",
    "Watch {first}'s first-step explosiveness — it tells you everything about how {team_name}'s defense will set the tone.",
    "One big play from {first} is often all {team_name} needs to swing the game in their favor.",
    "{first}'s backfield-penetration ability puts any offense in difficult down-and-distance situations versus {team_name}.",
    "The tackling efficiency {first} brings on early downs keeps the chains from moving on {team_name}.",
    "{first} winning the one-on-one battle on the edge is what makes the rest of {team_name}'s defense easier.",
    "{team_name}'s defense takes on a completely different personality when {first} is operating at full speed.",
    "A sack or a forced fumble from {first} is the kind of play that {team_name} has built its defensive identity around.",
    "The motor {first} brings to every snap is infectious — {team_name}'s defense feeds off that energy.",
    "{first} sets the edge, establishes containment, and forces the quarterback into trouble; {team_name} wins because of it.",
    "The punt chart gets tilted significantly by {first}'s ability to shorten drives for {team_name}.",
    "Containing the opposing skill players is easier for {team_name} when {first} is collapsing the pocket.",
    "{first} is the standard-bearer for {team_name}'s defensive identity — everyone else follows his lead.",
    "The ability to convert pressure into sacks gives {first} elite value within {team_name}'s scheme.",
    "{first} showing up in the backfield not only disrupts plays but destroys confidence in the opposing offense.",
    "{team_name} wins time-of-possession battles partly because {first} forces three-and-outs at key moments.",
    "The alignment flexibility {first} has gives {team_name} more defensive pre-snap options than any other unit.",
    "When {first} gets a clean lane, the result is usually a highlight for {team_name} and a headache for the offense.",
    "{first}'s interception range in coverage has already changed outcomes for {team_name} this season.",
    "The tackling form {first} maintains under pressure is a technical skill that saves {team_name} touchdowns.",
    "{first} reads the quarterback's eyes better than any defender on the {team_name} roster.",
    "Scheming to avoid {first} with protection shifts burns an offense's best plays before the snap for {team_name}.",
    "{team_name}'s turnover margin improves dramatically in games when {first} generates a big defensive play.",
    "The presence {first} commands at the line of scrimmage pre-snap is a free advantage for {team_name}.",
    "{first} making the right gap choice on the blitz is what turns pressure schemes into the best part of {team_name}'s defense.",
    "When {first} creates a negative play, {team_name}'s offense gets better starting position to build on.",
    "The consistent snap-to-snap effort from {first} is the standard the entire {team_name} defense holds itself to.",
    "{first} has the length and burst to close on screens before they develop — a critical skill against spread teams facing {team_name}.",
    "Stopping the other team's best player is what {first} does — and {team_name} sends him to do it weekly.",
    "{first}'s quickness off the line of scrimmage dictates blocking assignments before the play starts against {team_name}.",
    "The coverage extension ability of {first} makes {team_name}'s zone concepts nearly impossible to exploit.",
    "Every coordinator that faces {team_name} has to design a specific plan to neutralize {first} — most fall short.",
    "The disruption that {first} causes in the backfield filters through every layer of the offense facing {team_name}.",
    "{first}'s hand technique and leverage at the point of attack are among the best tools {team_name} has defensively.",
    "Blitzing {first} off the edge is the play {team_name} calls when it needs to take control of the game.",
    "{team_name} is capable of a shutdown defensive performance whenever {first} is making life difficult for the offense.",
    "The pass rush {first} generates does not just create sacks — it creates incompletions and off-target throws that help {team_name}.",
    "When {first} is in the backfield before the ball is released, {team_name} wins every time.",
    "The energy {first} plays with is the kind of thing coaches cannot teach — {team_name} is lucky to have it.",
    "{first}'s pre-snap alignment ability gives {team_name}'s defense built-in protection advantages on key plays.",
    "{team_name}'s biggest defensive plays this season have a common denominator: {first} in the backfield at the right time.",
    "The discipline {first} shows against misdirection plays is exactly why {team_name} can trust him on key downs.",
    "Watching {first} diagnose a screen pass before it develops is the best teaching film any defensive coordinator has for {team_name}.",
    "{first}'s ability to stay in his lane while still collapsing the pocket gives {team_name} a complete edge-rushing package.",
    "When {first} wins in coverage and in the pass rush on the same series, {team_name} is at its absolute best.",
    "{team_name}'s ability to generate three-and-outs in critical moments traces directly to {first}'s disruption.",
    "{first}'s relentless pursuit on plays that initially go away from him creates tackler-from-behind highlights for {team_name}.",
    "{team_name} trusts {first} on the most important defensive snaps of the game — there are usually several of them.",
    "{first}'s batting of passes at the line of scrimmage turns the intermediate routes into a guessing game for any QB against {team_name}.",
    "{first} versus the opposing quarterback is the matchup that decides where the game script goes for {team_name}.",
    "The veteran awareness {first} shows in coverage tells the QB where he cannot go — and that limits the offense facing {team_name}.",
    "When {first} wins the leverage battle at the line of scrimmage, {team_name}'s entire run defense stiffens.",
    "The consistency of {first}'s effort across an entire game is what gives {team_name}'s defense its staying power.",
    "A defense anchored by {first} can compete in any game — {team_name} proved that repeatedly this season.",
    "{first} in run support is as valuable as his pass rush; {team_name} does not have to cheat either way because of him.",
    "The film room preparation {first} brings to gameday gives {team_name} a defender who is almost never surprised.",
    "{first} winning at the point of attack on first down makes every other defensive call easier for {team_name}.",
    "{team_name} has its best defensive success rate in games when {first} records at least one big negative play.",
    "The key-play production from {first} raises the floor of {team_name}'s defense even when the offense is grinding.",
    "Whether it is on a third-down sack or a crucial tackle for loss, {first} produces when {team_name} needs it most.",
    "{first} reads option concepts faster than any defender in the league — {team_name} is schemed to take advantage of that.",
    "There is no safer bet in the league than {first} giving maximum effort on every single play for {team_name}.",
    "The technical excellence {first} brings to the run-stopping role makes {team_name} nearly impossible to run against.",
    "{first}'s closing speed on ball carriers in the open field has eliminated several big-gain opportunities for {team_name}.",
    "{team_name}'s best defensive series this season usually features {first} in at least one disruptive role.",
    "Preparation and pure physicality combine in {first} to give {team_name} a defensive standout.",
    "The way {first} sets the edge on sweep plays is a skill that directly protects {team_name}'s run-defense numbers.",
]

# ---------------------------------------------------------------------------
# PROFILE PHRASES – contender  (content_type: "profile_contender")
# Plain strings – returned by detect_profile_storyline for dominant teams.
# ---------------------------------------------------------------------------
PROFILE_CONTENDER: list[str] = [
    "Rolling like a contender",
    "Playing the brand of football that wins championships",
    "Operating at full contender capacity",
    "The league-wide benchmark right now",
    "Competing at a level that demands respect from every opponent",
    "Every phase is clicking at the right time",
    "A roster that is hitting its ceiling at the best possible moment",
    "The early front-runner to claim the top line",
    "Making winning look routine and repeatable",
    "Firing on all cylinders and not showing signs of slowing",
    "The team that opponents are building their week around stopping",
    "Setting the standard that every other team is chasing",
    "A model of consistency in a league where consistency is rare",
    "The team that has answered every challenge thrown at it",
    "Winning games that they are expected to win and a few they are not",
    "As close to a complete team as this league has seen this season",
    "The team that looks most prepared on game day, week after week",
    "Playing complementary football at a level few teams achieve",
    "The defining characteristic of their season so far is the ability to win close games",
    "A team that shows up differently when the stakes are highest",
    "A clear statement team emerging in this league",
    "Building a resume that will be hard to ignore come playoff time",
    "The team that other coaches use in their film sessions as the model",
    "This roster is peaking at exactly the right point in the season",
    "Confidence is not a problem here; execution backs up the belief",
    "Winning the hidden-stats battle — turnovers, third downs, and red zone — every week",
    "The team that controls the game tempo better than anyone in the league",
    "A team whose wins are more impressive than their record even reflects",
    "Entering every game as the favorite — and backing it up consistently",
    "Showing no weakness that any opponent has been able to consistently exploit",
]

# ---------------------------------------------------------------------------
# PROFILE PHRASES – struggling  (content_type: "profile_struggling")
# Plain strings – returned by detect_profile_storyline for struggling teams.
# ---------------------------------------------------------------------------
PROFILE_STRUGGLING: list[str] = [
    "Under pressure to stop the slide",
    "Looking for answers that have been elusive all season",
    "Navigating the hardest stretch of the schedule while searching for consistency",
    "The record does not lie, and the path forward requires real changes",
    "A team that has underperformed against its talent level",
    "Trying to find the version of themselves that showed up in their wins",
    "The losses are piling up and the adjustments have not arrived yet",
    "Every week brings a new test that this team has not yet shown it can pass",
    "The potential is obvious; the results have been painful",
    "A locker room that needs a momentum-changing performance, and soon",
    "The identity of this team has been unclear and the standings reflect it",
    "Inconsistency has been the signature of this season so far",
    "The talent is there; the execution has been the missing piece",
    "This program needs a signature win to reset the conversation around it",
    "Searching for the formula that turns close losses into close wins",
    "Opposing defenses have found a pattern, and adjustments have been slow",
    "The margin between where this team is and where it could be is frustrating",
    "A team trying to stop the bleeding and find any traction",
    "The record tells the story; this team has not put together a full game",
    "Urgency is not optional anymore — every remaining game is critical",
    "The season is not over, but the window to save it is narrowing",
    "This team has shown it can compete but not yet shown it can finish",
    "Every tough game has revealed something the coaching staff must address",
    "The players know what is needed; the challenge is delivering it consistently",
    "Adversity has defined this season — the question is whether they will respond",
    "A tough stretch has revealed cracks that need attention immediately",
    "The early promise of this team has been challenged by a run of difficult results",
    "Playing below the level the roster is capable of — something needs to break through",
    "A team that is not broken, just looking for the right combination",
    "The standings create urgency that was not present three weeks ago",
]

# ---------------------------------------------------------------------------
# PROFILE PHRASES – turnover dominant  (content_type: "profile_turnover")
# Plain strings – high turnover differential teams.
# ---------------------------------------------------------------------------
PROFILE_TURNOVER: list[str] = [
    "Winning the possession battle lately",
    "The turnover margin is a real competitive advantage for this team",
    "Taking the ball away more often than anyone in recent weeks",
    "Defensive opportunism is feeding the offense with extra possessions",
    "The plus-turnover teams in this league tend to win — this team is one of them",
    "Ball security on one side and forced turnovers on the other",
    "Winning the hidden game — turnovers — at a high rate",
    "The special teams and defense are combining to create short fields consistently",
    "Forcing turnovers at will is the statistical driver of their winning streak",
    "Their ability to take the ball away gives the offense more attempts than their peers",
    "The turnover battle is the game within the game — and this team wins it",
    "Creating extra possessions through turnovers is the engine of their success",
    "Offense built on short fields and extra attempts thanks to a disruptive defense",
    "Turnover margin is the quiet reason they outperform their yardage numbers",
    "Playing keep-away from the opponent's offense is the tactical specialty of this roster",
    "The hidden stats tell a story of a team built to win the possession game",
    "Forcing one more turnover per game than they commit is the whole formula",
    "Their takeaway rate is directly tied to their wins — it is no coincidence",
    "Ball-hawking defense and disciplined offense is the core identity of this team",
    "Thriving on opponent mistakes and protecting the ball themselves",
]

# ---------------------------------------------------------------------------
# PROFILE PHRASES – offense dominant  (content_type: "profile_offense")
# Plain strings – high-scoring teams.
# ---------------------------------------------------------------------------
PROFILE_OFFENSE: list[str] = [
    "Offense is carrying real momentum",
    "The scoring output has been among the best in the league lately",
    "Operating the most efficient offense in terms of points per possession",
    "The passing game and the run game have been firing in tandem",
    "A team that can score in any way necessary at any point in the game",
    "Putting up points so consistently that the defense can play freely",
    "The offensive rhythm of this team has carried them through tough stretches",
    "Points per game has been the key number driving this team's record",
    "The most prolific offensive stretch of the season is happening right now",
    "Red-zone efficiency and big plays have defined the offensive production",
    "Scoring points with ease is what this team does — opponents know the challenge",
    "The playmakers have been at their best when their team needs them most",
    "Building leads quickly has taken the pressure off every other part of the game",
    "The offensive playbook is among the deepest in the league, and it shows",
    "Finding the end zone on a majority of their drives is what this offense does",
    "The creativity of the offensive design keeps defenses unsettled every week",
    "Point production is not the concern; protecting the ball while scoring is the key",
    "Playing at an offensive pace that very few teams are equipped to match",
    "The explosiveness on offense is what puts them over the top in close games",
    "Scoring early and often is both the strategy and the result for this team",
]

# ---------------------------------------------------------------------------
# PROFILE PHRASES – defense dominant  (content_type: "profile_defense")
# Plain strings – stingy-defense teams.
# ---------------------------------------------------------------------------
PROFILE_DEFENSE: list[str] = [
    "Defense is keeping them in every game",
    "Allowing fewer points per game than almost anyone in the league",
    "The defensive identity of this team is the most consistent part of their game",
    "Holding opponents under their scoring average and keeping games winnable",
    "A defense that carries the team when the offense struggles",
    "The opponent scoring output has been suppressed to near-record levels",
    "Points against is the best number on this team's stat sheet",
    "Making every possession feel like a grind for any offense they face",
    "The defensive scheme has proven difficult to crack, week after week",
    "Winning games 17-13 is not a failure — it is the identity of this team",
    "Turning the opponent's best drive into a field goal or a punt",
    "The backfield disruption creates a scoring-suppression effect that wins games",
    "Defending the red zone at an elite rate is the foundation of their success",
    "Living on three-and-outs and short fields created by the defense",
    "A team whose defensive numbers would rank among the best in any era",
    "Allowing their opponents to grind but rarely break through is the hallmark",
    "The defensive coordinator deserves recognition for how few points this team allows",
    "Opponents score less against this team than against anyone else this season",
    "The defense has already saved three games from going the wrong direction",
    "Playing sound team defense with no clear weak spot is the identity here",
]

# ---------------------------------------------------------------------------
# PROFILE PHRASES – neutral  (content_type: "profile_neutral")
# Plain strings – competitive but unspecial teams.
# ---------------------------------------------------------------------------
PROFILE_NEUTRAL: list[str] = [
    "Trying to build weekly momentum",
    "Looking for the consistency to match their talent level",
    "A team that can beat anyone but has not yet put together a streak",
    "Playing well enough to compete but not yet well enough to dominate",
    "Building block performances are happening; the wins need to come in bunches",
    "A roster full of potential that has yet to translate into consistent results",
    "Competitive in every game but still searching for the breakthrough win",
    "Playing within themselves while waiting for a performance that raises the ceiling",
    "A team that looks dangerous in spurts but cannot sustain it yet",
    "The formula for winning is there; executing it for four full quarters is the project",
    "Every week is a chance to turn the page and find the identity this team is looking for",
    "Close games and narrow margins are the story so far — that can break either way",
    "This team has not yet found a signature mode of winning but the pieces are there",
    "Making progress but still a step away from turning progress into wins",
    "The missing ingredient has been identified; the challenge is producing it consistently",
    "A team that needs to find its best version quickly as the schedule gets harder",
    "Doing enough to stay relevant while the rest of the league sorts itself out",
    "Game-by-game improvement is the honest assessment of this team's season so far",
    "The roster is capable of competing at a higher level than the record suggests",
    "A team whose best football may still be ahead of them this season",
    "The margins in every game this team plays are close — and that will eventually go their way",
    "Playing hard every week but still chasing that combination of execution and fortune",
    "A team with clear strengths that has not yet learned how to lean on them consistently",
    "The ceiling here is higher than the floor suggests — one performance away from a turning point",
    "Grinding through the schedule without breakthroughs but without collapse either",
    "A competitive team still finding its identity under real-game conditions",
    "The wins that come will not be pretty, but they will count the same on the board",
    "Every week the effort is there; the margin of error for this team is just very thin",
    "A team that needs to figure out how to close games — when they do, everything changes",
    "Optimism is still warranted here; the sample size is small enough to turn it around quickly",
]

# ---------------------------------------------------------------------------
# WEEKLY NEWS OPENERS  (content_type: "weekly_news_opener")
# Template strings – use .format(week=, top_team=, away=, home=)
# ---------------------------------------------------------------------------
WEEKLY_NEWS_OPENERS: list[str] = [
    "Week {week} is shaping the season fast, with {top_team} trying to protect position while challengers close in.",
    "The Week {week} slate arrives with {top_team} at the top and everyone else trying to close the gap.",
    "A critical stretch of the schedule deepens as Week {week} delivers games that will be dissected for weeks.",
    "Week {week} is here, and the most interesting storylines are only beginning to take shape.",
    "As Week {week} begins, the league's competitive balance is being tested in real time.",
    "The standings are settling into something real, and Week {week} could lock several fates in place.",
    "Week {week} carries the weight of a season in progress — every result feels irreversible.",
    "Momentum has never been more fragile or more meaningful than it is entering Week {week}.",
    "Week {week} shakes up the schedule order and may well shake up the standings too.",
    "There is a different energy around Week {week} — the games feel heavier than they did in September.",
    "Week {week} is the kind of slate that separates early-season noise from genuine contenders.",
    "The plot thickens as Week {week} drops into a season already full of compelling narratives.",
    "Surprises, statements, and setting up the postseason — Week {week} promises all three.",
    "Every team entering Week {week} knows the arithmetic — wins keep them in it, losses complicate the math.",
    "The league is watching closely as Week {week} presents a set of games with direct playoff implications.",
    "Week {week} does not offer any soft matchups for teams in the standings race.",
    "The race gets more interesting with each passing week, and Week {week} could be the most important yet.",
    "The {week}-week mark of the season is a reality check — Week {week} is delivering it.",
    "Not every week reshapes the standings conversation, but Week {week} has the ingredients to do it.",
    "Week {week} is one of those rare collections of games where almost every result matters for multiple teams.",
    "With the regular season slipping away, Week {week} carries a quiet urgency for every team in the middle.",
    "The race at the top is the story, but the fight for the final playoff spots defines Week {week} equally.",
    "Week {week} feels pivotal — not because we are told it is, but because the results will prove it.",
    "The narrative of this league season gets its next chapter in Week {week}.",
    "Every coaching staff spent the week scheming for games that could define their season in Week {week}.",
    "This is the week teams find out if the winning streak was real or the losing streak was a fluke.",
    "Week {week} is when the league's competitive hierarchy starts to crystalize from top to bottom.",
    "Preparing for Week {week} required every team to make bold decisions — we find out today if they were right.",
    "All the offseason preparation, draft picks, and free agency moves come down to weeks exactly like Week {week}.",
    "The best storyline in the league runs straight through Week {week}.",
    "Week {week} refuses to sit quietly in the middle of the season — these games demand attention.",
    "With playoff spots beginning to take shape, the urgency of Week {week} is unmistakable.",
    "Teams that need to win are matched up against teams that need to win — that is the theme of Week {week}.",
    "The Week {week} schedule was built for moments exactly like this, with the standings this close.",
    "How teams respond to pressure is about to be revealed across every game on the Week {week} slate.",
    "Week {week} arrives and the league's competitive balance is the most compelling storyline going.",
    "The anticipation around Week {week} is not manufactured — the games genuinely matter.",
    "Any team that is not laser focused entering Week {week} is going to fall behind quickly.",
    "The outcomes from Week {week} will generate the most talking points of any week so far.",
    "Week {week} is the kind of week that gets referenced in the postseason when teams explain their seeds.",
    "Welcome to Week {week}: where the dreams are clear, the pressure is real, and the games are the story.",
    "The season finds its next defining moment in Week {week} — someone has to rise and someone has to absorb a hit.",
    "Every game on the Week {week} board carries implications that do not stop at the final whistle.",
    "Week {week} is the week when separations begin to happen — in the standings and in the narrative.",
    "The schedule gave us Week {week}: a set of games that will force every team to prove something.",
    "There are no hiding spots in Week {week} — the most competitive teams will be tested.",
    "Week {week} begins, and the outcomes will arrive faster than anyone is ready for.",
    "The best football of the season is happening right now, and Week {week} is the proof.",
    "Week {week}: a full slate of games that each have the weight of a month behind them.",
    "Getting to Week {week} with options still alive is an accomplishment — defending them is the next task.",
    "Week {week} is the kind of week that makes even casual observers stop and pay attention.",
    "Every team enters Week {week} with something to prove and the standings waiting to reflect the answer.",
    "The season has arrived at the inflection point — Week {week} is where things either accelerate or derail.",
    "Week {week} games feel different because the context has deepened and the stakes have risen.",
    "The Week {week} preview almost writes itself when the games are this loaded with meaning.",
    "This is the week teams find out whether their preparation has matched the moment — Week {week} is here.",
    "Week {week} is the natural culmination of everything that has happened so far, compressed into one slate.",
    "The league's best teams are about to be tested by the league's hungriest teams in Week {week}.",
    "Week {week} carries the emotional weight of a deep season already full of turning points.",
    "Whether contenders or challengers, every team in Week {week} has something important on the line.",
    "The pressure is mutual in Week {week} — no team arrives without a need to perform.",
    "Welcome to Week {week}: the games that shape the rest of what the season will become.",
    "Week {week} is perfect timing for the league to produce something memorable.",
    "Something shifts every year around this part of the season — Week {week} is where it happens.",
    "The race clarifies and the pretenders drop off — Week {week} has that kind of thinning-of-the-herd energy.",
    "Week {week}: the stakes are real, the talent is on display, and the results will echo.",
    "It is Week {week}, and the league is at its most interesting point of the season.",
    "The Week {week} matchups are the direct result of every decision made in the weeks prior.",
    "Week {week} has a feel-it-in-the-bones importance that only shows up at certain points in a season.",
    "Every team that walks away from Week {week} with a win has earned something that matters.",
    "Week {week} is a window that opens once and closes fast — teams prepared for it will show it today.",
    "The most consequential stretch of the regular season continues in Week {week}.",
    "The stories we will tell about this season get written in weeks exactly like Week {week}.",
    "Week {week} delivers the kind of football that makes franchise leagues worth running.",
    "A loaded slate of games makes Week {week} mandatory viewing for every team's film room.",
    "The outcomes in Week {week} will directly shape what the playoff bracket looks like.",
    "There is no downtime in Week {week} — every snap carries the full weight of the season.",
    "Week {week} is the antidote to any notion that this season lacks drama.",
]

# ---------------------------------------------------------------------------
# WEEKLY NEWS BODY LINES  (content_type: "weekly_news_body")
# Template strings – use .format(week=, top_team=, away=, home=)
# These are the mid-article sentences after the opener.
# ---------------------------------------------------------------------------
WEEKLY_NEWS_BODY_LINES: list[str] = [
    "The headline matchup this week is {away} at {home}, a game that could swing both momentum and seeding pressure.",
    "{away} vs. {home} is the game that every other team will be watching closely on the results board.",
    "The top of the standings features {top_team} continuing to make the case they are the class of the league.",
    "Across the board, teams are being forced to prove whether their records match their long-term ceiling.",
    "Stat races are tightening, and every result is beginning to carry playoff context.",
    "This slate feels like one that can redraw how the league is discussed next week.",
    "The standings are close enough that a two-game swing in either direction matters enormously.",
    "The teams who win this week are buying themselves the most important commodity: options.",
    "{top_team} sitting at the top of the standings is the story that frames everything else this week.",
    "Every team in playoff contention needs a win today; very few will get one.",
    "The drama is not manufactured — it is the natural consequence of a closely contested league.",
    "Executing through adversity is what separates the best teams from the rest of the field.",
    "With meaningful games at every position in the standings, Week {week} has no throwaway matchups.",
    "The offensive and defensive stat leaders will both be watching today's results carefully.",
    "Every coordinator in the league is making adjustments — the best ones show up in wins this week.",
    "The player of the week recognition will be earned in unusually high-pressure circumstances today.",
    "Star players in big games: Week {week} has them in every corner of the bracket.",
    "The analytics tell a story of extremely even competition — today's results will make it less even.",
    "{top_team} cannot coast; every team below them is pushing for the chance to take the top line.",
    "Teams playing from behind in the standings have nothing to lose — that is what makes them dangerous.",
    "Whether the game turns on a turnover, a kick, or a fourth-down stop, outcomes today will matter.",
    "The competition has intensified because the margin for error has shrunk.",
    "Today's score lines will generate the discussion that drives the next week of preparation.",
    "Field goals, touchdown drives, and fourth-quarter decisions will all carry outsized weight today.",
    "The teams playing their best football right now are going to separate themselves from the pack today.",
    "Every roster built for this type of grind-it-out schedule is going to show it in Week {week}.",
    "Win probability does not capture the full story — execution and chance will both play a role today.",
    "Turnover margins, third-down conversions, and red-zone stops will write the Week {week} story.",
    "Fans of teams in the middle of the standings know the truth: this week is their whole season.",
    "The league's best performances do not always come in the biggest games, but today they might.",
    "Score differentials in close games do not matter — it is the two points in the standings that count.",
    "The depth of every roster is tested in weeks when the weather, preparation, and pressure all align.",
    "Every team has been preparing for today; the difference will come down to who executes better.",
    "Not all points are equal — the ones scored in games like today's are worth more.",
    "The stat leaders in the league will be tested by the best defenses they have faced this season.",
    "The Week {week} result between {away} and {home} will resonate in the standings for weeks.",
    "There is a fine line between winning and losing in a league this competitive — today the line becomes visible.",
    "It only takes one result to swing the entire playoff picture — Week {week} might produce that result.",
    "The intangibles — crowd noise, travel, injury management, rest — all come into play on a week like this one.",
    "Everyone on the fringe of the playoff race enters Week {week} knowing they cannot afford another loss.",
    "The offensive coordinators have spent the week looking for a weakness — today we find out if they found one.",
    "Taking nothing for granted is the only approach that works in a league this competitive during Week {week}.",
    "The teams that control the line of scrimmage in Week {week} will control the standings.",
    "Both the player-of-the-year race and the team-of-the-year conversation get their next data point today.",
    "Defense, offense, and special teams are each going to matter in ways that could define Week {week}.",
    "The emotional component of big-week football is real, and the teams that channel it best win.",
    "Today is about finding out which teams are built for the moments that stretch the entire season.",
    "What {away} does against {home}'s defense will tell us everything we need to know about their ceiling.",
    "Not one game on the Week {week} board lacks significance — that is the sign of a legitimately competitive league.",
    "The results from today will shift at least five teams' playoff probability in some direction.",
    "It takes more than talent to win weeks like this — it takes preparation, execution, and fortune.",
    "When the dust settles on Week {week}, the picture at the top and bottom of the standings will be clearer.",
    "The pressure on {top_team} to maintain is equal to the pressure on their competitors to close the gap.",
    "Momentum built over the last few weeks can be extended or ended in a single afternoon.",
    "The best coaching decisions of the season are going to happen under the most pressure in Week {week}.",
    "Every play-action fake, every blitz disguise, every timeout decision counts double in Week {week}.",
    "The team that protects the ball best in Week {week} will almost certainly move up in the standings.",
    "The physical toll of a long season shows up most clearly in weeks exactly like this one.",
    "Health, depth, and game-planning are all being maximized by the teams who need a win the most today.",
    "Week {week} will be studied in post-season film sessions as the week that shaped the playoff order.",
    "The game-within-the-game subplots are as compelling as the final scores this week.",
    "This week is a stress test for every team's core identity — who shows up as advertised?",
    "There are two types of teams entering Week {week}: ones that handle pressure, and ones that don't.",
    "What made last week interesting was the results; what makes this week interesting is the anticipation.",
    "The teams with the clearest identity heading into Week {week} are going to look the sharpest on the field.",
    "Strategy, execution, and willpower — all three are going to be required to walk away with a win today.",
    "It is Week {week}, and the scoreboard waits for no one.",
    "The combination of high stakes and evenly matched rosters makes Week {week} the best version of this league.",
    "This is what franchise leagues are designed for: a Week {week} slate where almost every result matters.",
    "The post-game conversations after Week {week} will begin immediately and run all the way to game day next week.",
    "Execution at the highest level, under pressure, in a meaningful game — that is the Week {week} ask.",
    "Today is about showing up when it counts — and in Week {week}, everyone counts.",
    "The league is in its best stretch of football, and Week {week} is the highlight so far.",
    "Across the field, the best competition of the season is playing out in real time during Week {week}.",
    "{away} and {home} both walked into the week knowing this game could be the one that defines their season.",
    "Wherever you look on the Week {week} board, you find a game with real consequences.",
    "The ability to finish close games is what separates the top-seeded teams from the middle of the pack today.",
    "Week {week} is the pressure cooker that every team knew was coming when they read the original schedule.",
    "The final stretch of the season starts with games that require every team to be at its best.",
]

# ---------------------------------------------------------------------------
# HEADLINE TEMPLATES – line 1 (top team leader)  (content_type: "headline_line1")
# Template strings – use .format(top_team=, top_record=)
# ---------------------------------------------------------------------------
HEADLINE_LINE1: list[str] = [
    "{top_team} leads the league at {top_record}, setting the pace in the standings race.",
    "At {top_record}, {top_team} is the team every other roster is chasing right now.",
    "{top_team} sits atop the standings at {top_record} — the benchmark for the rest of the league.",
    "The league's best record belongs to {top_team} at {top_record}, and they are not looking back.",
    "{top_team} posts {top_record} to maintain the top seed heading into another competitive week.",
    "Nobody in the league is playing better than {top_team}, who stand at {top_record}.",
    "{top_team} at {top_record}: the best team in the league based on what we have seen so far.",
    "The top of the standings belongs to {top_team} at {top_record} — and they have earned every win.",
    "With a record of {top_record}, {top_team} has created real separation at the top of the standings.",
    "{top_record} is the number, and {top_team} is the team — the leader of the pack this season.",
    "{top_team} continues to set the gold standard at {top_record}, the best record in the league.",
    "Standing alone at {top_record}, {top_team} is the definition of the standard-setter in this league.",
    "Consistency is the story at the top — {top_team} at {top_record} continues to win.",
    "{top_team} holds the top seed at {top_record}: a statement of sustained excellence.",
    "The first thing on every team's schedule this week is watching what {top_team} does at {top_record}.",
    "At {top_record}, {top_team} is the team everyone is scheming against — and so far no one has cracked the code.",
    "The standings start and end with {top_team}'s {top_record} as the standard to measure against.",
    "The {top_record} record by {top_team} is the most relevant number in the league standings right now.",
    "{top_team} at {top_record}: a reminder of what consistent execution looks like across every phase.",
    "No team in the league can match {top_team}'s résumé right now — {top_record} says it all.",
]

# ---------------------------------------------------------------------------
# HEADLINE TEMPLATES – line 3 (passing leader)  (content_type: "headline_line3")
# Template strings – use .format(passer=, pass_yards=, pass_tds=)
# ---------------------------------------------------------------------------
HEADLINE_LINE3: list[str] = [
    "{passer} is the top passer with {pass_yards} yards and {pass_tds} touchdowns.",
    "Through the air, {passer} leads the league with {pass_yards} yards and {pass_tds} scores.",
    "{passer} owns the passing leaderboard: {pass_yards} yards and {pass_tds} touchdowns on the season.",
    "The best arm in the league belongs to {passer} — {pass_yards} yards and {pass_tds} touchdowns prove it.",
    "{passer} has been untouchable throwing the ball: {pass_yards} yards and {pass_tds} TDs so far.",
    "In the passing game, nobody beats {passer}'s {pass_yards} yards and {pass_tds} touchdowns.",
    "{passer} is writing the best passing line in the league: {pass_yards} yards, {pass_tds} scores.",
    "Quarterbacks across the league are looking up at {passer}'s {pass_yards} yards and {pass_tds} touchdowns.",
    "{passer} is the standard at quarterback — {pass_yards} passing yards and {pass_tds} touchdowns.",
    "The aerial game belongs to {passer} this season: {pass_yards} yards and {pass_tds} scores.",
    "{passer} is in the middle of one of the best passing seasons in league history: {pass_yards} yards, {pass_tds} TDs.",
    "Arm talent, command, and results — {passer} has it all at {pass_yards} yards and {pass_tds} touchdowns.",
    "The {pass_yards}-yard, {pass_tds}-touchdown season from {passer} is the best passing output in the league.",
    "{passer} picking apart defenses: {pass_yards} yards through the air and {pass_tds} touchdowns.",
    "The passing race is not close — {passer} leads everyone with {pass_yards} yards and {pass_tds} touchdowns.",
    "Nobody moves the chains through the air like {passer}: {pass_yards} yards and {pass_tds} TDs.",
    "{passer} at {pass_yards} passing yards and {pass_tds} touchdowns: the standard for quarterbacks this season.",
    "The most prolific passer in the league is {passer} at {pass_yards} yards and {pass_tds} scores.",
    "{passer} is in command of the passing stats: {pass_yards} yards and {pass_tds} touchdowns lead the league.",
    "Air it out: {passer} leads the league throwing the ball with {pass_yards} yards and {pass_tds} touchdowns.",
]

# ---------------------------------------------------------------------------
# HEADLINE TEMPLATES – line 4 (rushing leader)  (content_type: "headline_line4")
# Template strings – use .format(rusher=, rush_yards=)
# ---------------------------------------------------------------------------
HEADLINE_LINE4: list[str] = [
    "{rusher} leads all rushers with {rush_yards} yards on the ground.",
    "The ground game belongs to {rusher} — {rush_yards} yards and counting.",
    "{rusher} is the best rusher in the league at {rush_yards} yards on the season.",
    "Nobody has been more punishing on the ground than {rusher}: {rush_yards} rushing yards.",
    "{rusher} owns the rushing leaderboard with {rush_yards} yards — the ground game is his.",
    "The run game is alive and well, and {rusher} is leading it at {rush_yards} yards.",
    "{rusher} at {rush_yards} rushing yards is the gold standard for the position this season.",
    "Ground and pound: {rusher} leads the league with {rush_yards} yards on the ground.",
    "{rusher} has punished tacklers all season to the tune of {rush_yards} rushing yards.",
    "The best running back in the league is playing his best football: {rusher} at {rush_yards} yards.",
    "{rusher} sets the rushing pace with {rush_yards} yards — the engine of his team's run game.",
    "No one grinds for yards like {rusher}: {rush_yards} rushing yards and the league leader.",
    "{rush_yards} rushing yards is the number; {rusher} is the name above it on the leaderboard.",
    "Controlling the line of scrimmage starts with {rusher} — {rush_yards} yards says so.",
    "{rusher} is making a case for the best ground game in the league at {rush_yards} yards.",
    "The rushing title right now goes to {rusher}: {rush_yards} yards of proof.",
    "{rusher} keeps churning out yards — {rush_yards} on the ground this season.",
    "The feature back in this league's best rushing offense is {rusher} at {rush_yards} yards.",
    "{rush_yards} yards on the ground for {rusher}: relentless running, consistent production.",
    "No one has been more consistent on the ground than {rusher}: {rush_yards} yards and the top spot.",
]

# ---------------------------------------------------------------------------
# HEADLINE TEMPLATES – line 5 (receiving leader)  (content_type: "headline_line5")
# Template strings – use .format(receiver=, rec_yards=, rec_tds=)
# ---------------------------------------------------------------------------
HEADLINE_LINE5: list[str] = [
    "{receiver} tops the receiving charts with {rec_yards} yards and {rec_tds} touchdowns.",
    "In the pass-catching game, {receiver} is the standard with {rec_yards} yards and {rec_tds} scores.",
    "{receiver} leads all receivers at {rec_yards} yards and {rec_tds} touchdowns.",
    "The best wide receiver season in the league belongs to {receiver}: {rec_yards} yards, {rec_tds} TDs.",
    "{receiver} is the go-to target this season — {rec_yards} yards and {rec_tds} touchdowns lead the league.",
    "Nobody catches the ball better than {receiver} this season: {rec_yards} yards, {rec_tds} scores.",
    "{receiver}'s receiving line is best in the league: {rec_yards} yards and {rec_tds} touchdowns.",
    "The receiving title race ends with {receiver}: {rec_yards} yards and {rec_tds} touchdowns.",
    "{rec_yards} receiving yards and {rec_tds} touchdowns for {receiver}: elite production at the position.",
    "{receiver} continues to separate from the field: {rec_yards} yards, {rec_tds} touchdowns.",
    "Quarterbacks dream of having a weapon like {receiver}: {rec_yards} yards and {rec_tds} scores.",
    "The best route-runner, the best producer: {receiver} at {rec_yards} yards and {rec_tds} touchdowns.",
    "{receiver} leads all pass catchers with {rec_yards} receiving yards and {rec_tds} touchdowns.",
    "The receiving leaderboard starts with {receiver}: {rec_yards} yards and {rec_tds} TDs.",
    "No one in the league has been more dangerous as a receiver than {receiver}: {rec_yards} yards, {rec_tds} TDs.",
    "{receiver} is building a receiving season for the record books: {rec_yards} yards, {rec_tds} scores.",
    "Making the big catch at the biggest moments: {receiver} at {rec_yards} yards, {rec_tds} touchdowns.",
    "The top wideout stat line this season belongs to {receiver}: {rec_yards} yards and {rec_tds} TDs.",
    "{rec_yards} yards and {rec_tds} touchdowns for {receiver} — elite-tier receiving production.",
    "{receiver} has been impossible to cover: {rec_yards} receiving yards and {rec_tds} touchdowns.",
]
